name: Feature Request
description: Suggest an idea for Justice Companion
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature!

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: A clear description of what you want to happen
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe alternatives you've considered
      placeholder: A clear description of any alternative solutions or features

  - type: dropdown
    id: area
    attributes:
      label: Feature Area
      description: Which part of the application does this feature relate to?
      options:
        - Cases Management
        - Evidence Management
        - Timeline/Deadlines
        - AI Features
        - Document Processing
        - User Interface
        - Authentication/Security
        - Settings/Configuration
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Would be useful
        - Important
        - Critical
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or mockups about the feature request

  - type: checkboxes
    id: terms
    attributes:
      label: Legal Disclaimer Acknowledgment
      description: Justice Companion provides legal INFORMATION, not legal ADVICE
      options:
        - label: I understand this feature should provide information, not legal advice
          required: true
