guardian:
  mode: continuous
  monitoring:
    file_watcher: true
    auto_scan_interval: 1800
    watch_paths:
    - .
    ignore_patterns:
    - .git
    - node_modules
    - __pycache__
    - .venv
    - dist
    - build
    - .guardian
  llm:
    use_free_tier: true
    free_tier_provider: gemini
    gemini_api_key: env:GOOGLE_API_KEY
    gemini_model: gemini-2.5-flash
    groq_api_key: env:GROQ_API_KEY
    groq_model: llama-3.3-70b-versatile
    tier_routing:
      rule_based:
      - linting
      - formatting
      - style
      free_ai:
      - refactoring
      - testing
      - documentation
      - code-quality
      - security
      - compliance
  ultrathink:
    enabled: true
