import { motion } from 'framer-motion';
import { X, AlertTriangle, Scale, CheckCircle, AlertCircle, ExternalLink, BookOpen } from 'lucide-react';
import { Card } from '../../../components/ui/Card.tsx';
import { Button } from '../../../components/ui/Button.tsx';
import type { CaseAnalysisResponse } from '../../../types/ai-analysis.ts';

interface CaseAnalysisDialogProps {
  onClose: () => void;
  analysis: CaseAnalysisResponse;
  isLoading?: boolean;
}

export function CaseAnalysisDialog({ onClose, analysis, isLoading }: CaseAnalysisDialogProps) {
  if (isLoading) {
    return (
      <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm p-4">
        <motion.div
          initial={{ opacity: 0, scale: 0.9 }}
          animate={{ opacity: 1, scale: 1 }}
          className="w-full max-w-4xl"
        >
          <Card variant="glass" className="p-8 text-center">
            <div className="flex flex-col items-center gap-4">
              <div className="h-12 w-12 animate-spin rounded-full border-4 border-primary-500 border-t-transparent" />
              <p className="text-lg text-white">Analyzing your case...</p>
              <p className="text-sm text-gray-400">Justice Companion AI is reviewing your case details</p>
            </div>
          </Card>
        </motion.div>
      </div>
    );
  }

  const getSeverityColor = (severity: string) => {
    switch (severity) {
      case 'critical':
        return 'text-red-400 bg-red-900/30 border-red-700';
      case 'high':
        return 'text-orange-400 bg-orange-900/30 border-orange-700';
      case 'medium':
        return 'text-yellow-400 bg-yellow-900/30 border-yellow-700';
      case 'low':
        return 'text-green-400 bg-green-900/30 border-green-700';
      default:
        return 'text-gray-400 bg-gray-900/30 border-gray-700';
    }
  };

  const getPriorityColor = (priority: string) => {
    switch (priority) {
      case 'urgent':
        return 'text-red-400 bg-red-900/30 border-red-700';
      case 'high':
        return 'text-orange-400 bg-orange-900/30 border-orange-700';
      case 'medium':
        return 'text-yellow-400 bg-yellow-900/30 border-yellow-700';
      case 'low':
        return 'text-green-400 bg-green-900/30 border-green-700';
      default:
        return 'text-gray-400 bg-gray-900/30 border-gray-700';
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm p-4 overflow-auto">
      <motion.div
        initial={{ opacity: 0, scale: 0.9, y: 20 }}
        animate={{ opacity: 1, scale: 1, y: 0 }}
        exit={{ opacity: 0, scale: 0.9, y: 20 }}
        transition={{ type: 'spring', stiffness: 300, damping: 25 }}
        className="w-full max-w-6xl my-8"
      >
        <Card
          variant="glass"
          className="overflow-visible"
          role="dialog"
          aria-modal="true"
          aria-labelledby="case-analysis-dialog-title"
        >
          {/* Header */}
          <div className="flex items-center justify-between border-b border-gray-700/50 pb-4 mb-6">
            <div>
              <h2
                id="case-analysis-dialog-title"
                className="text-2xl font-bold text-white flex items-center gap-2"
              >
                <Scale className="h-6 w-6 text-primary-400" />
                Case Analysis Results
              </h2>
              <p className="text-sm text-gray-400 mt-1">
                Generated by Justice Companion AI
              </p>
            </div>
            <Button
              onClick={onClose}
              variant="ghost"
              size="sm"
              icon={<X />}
              aria-label="Close case analysis dialog"
              className="rounded-full"
            />
          </div>

          <div className="space-y-6 max-h-[70vh] overflow-y-auto pr-2">
            {/* Legal Issues */}
            <section>
              <h3 className="text-lg font-semibold text-white mb-3 flex items-center gap-2">
                <AlertTriangle className="h-5 w-5 text-orange-400" />
                Legal Issues Identified
              </h3>
              <div className="space-y-3">
                {analysis.legalIssues.map((issue, index) => (
                  <Card key={index} variant="flat" className="p-4">
                    <div className="flex items-start justify-between gap-4">
                      <div className="flex-1">
                        <div className="flex items-center gap-2 mb-2">
                          <h4 className="font-medium text-white">{issue.title}</h4>
                          <span
                            className={`px-2 py-1 rounded text-xs font-medium border ${getSeverityColor(issue.severity)}`}
                          >
                            {issue.severity.toUpperCase()}
                          </span>
                        </div>
                        <p className="text-sm text-gray-300 mb-2">{issue.description}</p>
                        {issue.potentialImpact && (
                          <p className="text-xs text-gray-400 italic">
                            Impact: {issue.potentialImpact}
                          </p>
                        )}
                      </div>
                    </div>
                  </Card>
                ))}
              </div>
            </section>

            {/* Applicable Law */}
            <section>
              <h3 className="text-lg font-semibold text-white mb-3 flex items-center gap-2">
                <BookOpen className="h-5 w-5 text-blue-400" />
                Applicable UK Law
              </h3>
              <div className="space-y-3">
                {analysis.applicableLaw.map((law, index) => (
                  <Card key={index} variant="flat" className="p-4">
                    <h4 className="font-medium text-white mb-2">{law.statute}</h4>
                    <p className="text-sm text-gray-300 mb-2">{law.relevantSections}</p>
                    <p className="text-xs text-gray-400 italic mb-2">
                      How it applies: {law.howItApplies}
                    </p>
                    {law.citation && (
                      <a
                        href={law.citation}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="text-xs text-primary-400 hover:text-primary-300 flex items-center gap-1"
                      >
                        View statute
                        <ExternalLink className="h-3 w-3" />
                      </a>
                    )}
                  </Card>
                ))}
              </div>
            </section>

            {/* Recommended Actions */}
            <section>
              <h3 className="text-lg font-semibold text-white mb-3 flex items-center gap-2">
                <CheckCircle className="h-5 w-5 text-green-400" />
                Recommended Actions
              </h3>
              <div className="space-y-3">
                {analysis.recommendedActions.map((action, index) => (
                  <Card key={index} variant="flat" className="p-4">
                    <div className="flex items-start gap-3">
                      <div
                        className={`flex-shrink-0 w-8 h-8 rounded-full flex items-center justify-center text-sm font-bold ${getPriorityColor(action.priority)}`}
                      >
                        {index + 1}
                      </div>
                      <div className="flex-1">
                        <div className="flex items-center gap-2 mb-2">
                          <h4 className="font-medium text-white">{action.title}</h4>
                          <span
                            className={`px-2 py-1 rounded text-xs font-medium border ${getPriorityColor(action.priority)}`}
                          >
                            {action.priority.toUpperCase()}
                          </span>
                        </div>
                        <p className="text-sm text-gray-300 mb-2">{action.description}</p>
                        {action.timeframe && (
                          <p className="text-xs text-gray-400">
                            Timeframe: {action.timeframe}
                          </p>
                        )}
                      </div>
                    </div>
                  </Card>
                ))}
              </div>
            </section>

            {/* Evidence Gaps */}
            {analysis.evidenceGaps && analysis.evidenceGaps.length > 0 && (
              <section>
                <h3 className="text-lg font-semibold text-white mb-3 flex items-center gap-2">
                  <AlertCircle className="h-5 w-5 text-yellow-400" />
                  Evidence Gaps
                </h3>
                <div className="space-y-3">
                  {analysis.evidenceGaps.map((gap, index) => (
                    <Card key={index} variant="flat" className="p-4">
                      <div className="flex items-start justify-between gap-4">
                        <div className="flex-1">
                          <div className="flex items-center gap-2 mb-2">
                            <h4 className="font-medium text-white">{gap.missingEvidence}</h4>
                            <span
                              className={`px-2 py-1 rounded text-xs font-medium border ${getSeverityColor(gap.importance)}`}
                            >
                              {gap.importance.toUpperCase()}
                            </span>
                          </div>
                          <p className="text-sm text-gray-300 mb-2">
                            Why needed: {gap.whyNeeded}
                          </p>
                          {gap.suggestedSources && gap.suggestedSources.length > 0 && (
                            <div className="text-xs text-gray-400">
                              <p className="font-medium mb-1">Suggested sources:</p>
                              <ul className="list-disc list-inside space-y-1">
                                {gap.suggestedSources.map((source, idx) => (
                                  <li key={idx}>{source}</li>
                                ))}
                              </ul>
                            </div>
                          )}
                        </div>
                      </div>
                    </Card>
                  ))}
                </div>
              </section>
            )}

            {/* Complexity Score */}
            {analysis.estimatedComplexity && (
              <section>
                <h3 className="text-lg font-semibold text-white mb-3">
                  Case Complexity Assessment
                </h3>
                <Card variant="flat" className="p-4">
                  <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                    <div>
                      <p className="text-xs text-gray-400 mb-1">Overall Score</p>
                      <p className="text-2xl font-bold text-white">
                        {analysis.estimatedComplexity.overallScore}/10
                      </p>
                    </div>
                    <div>
                      <p className="text-xs text-gray-400 mb-1">Legal Complexity</p>
                      <p className="text-2xl font-bold text-white">
                        {analysis.estimatedComplexity.legalComplexity}/10
                      </p>
                    </div>
                    <div>
                      <p className="text-xs text-gray-400 mb-1">Evidence Strength</p>
                      <p className="text-2xl font-bold text-white">
                        {analysis.estimatedComplexity.evidenceStrength}/10
                      </p>
                    </div>
                    <div>
                      <p className="text-xs text-gray-400 mb-1">Est. Duration</p>
                      <p className="text-lg font-semibold text-white">
                        {analysis.estimatedComplexity.estimatedDuration}
                      </p>
                    </div>
                  </div>
                  {analysis.estimatedComplexity.keyFactors && (
                    <div className="mt-4 pt-4 border-t border-gray-700">
                      <p className="text-xs text-gray-400 mb-2">Key Complexity Factors:</p>
                      <ul className="list-disc list-inside space-y-1 text-sm text-gray-300">
                        {analysis.estimatedComplexity.keyFactors.map((factor, idx) => (
                          <li key={idx}>{factor}</li>
                        ))}
                      </ul>
                    </div>
                  )}
                </Card>
              </section>
            )}

            {/* AI Reasoning */}
            <section>
              <h3 className="text-lg font-semibold text-white mb-3">Analysis Reasoning</h3>
              <Card variant="flat" className="p-4">
                <p className="text-sm text-gray-300 whitespace-pre-wrap">
                  {analysis.reasoning}
                </p>
              </Card>
            </section>

            {/* Legal Sources */}
            {analysis.sources && analysis.sources.length > 0 && (
              <section>
                <h3 className="text-lg font-semibold text-white mb-3">Legal Sources</h3>
                <div className="space-y-2">
                  {analysis.sources.map((source, index) => (
                    <Card key={index} variant="flat" className="p-3">
                      <div className="flex items-center justify-between gap-2">
                        <div>
                          <p className="text-sm font-medium text-white">{source.title}</p>
                          <p className="text-xs text-gray-400">{source.type}</p>
                        </div>
                        {source.url && (
                          <a
                            href={source.url}
                            target="_blank"
                            rel="noopener noreferrer"
                            className="text-primary-400 hover:text-primary-300"
                          >
                            <ExternalLink className="h-4 w-4" />
                          </a>
                        )}
                      </div>
                    </Card>
                  ))}
                </div>
              </section>
            )}

            {/* Disclaimer */}
            <section>
              <Card variant="flat" className="p-4 bg-yellow-900/20 border border-yellow-700/50">
                <div className="flex gap-3">
                  <AlertTriangle className="h-5 w-5 text-yellow-400 flex-shrink-0 mt-0.5" />
                  <div>
                    <p className="text-sm font-medium text-yellow-200 mb-1">Important Disclaimer</p>
                    <p className="text-xs text-yellow-100/80">{analysis.disclaimer}</p>
                  </div>
                </div>
              </Card>
            </section>
          </div>

          {/* Footer */}
          <div className="flex gap-3 pt-6 mt-6 border-t border-gray-700/50">
            <Button
              onClick={onClose}
              variant="secondary"
              size="md"
              fullWidth
            >
              Close
            </Button>
          </div>
        </Card>
      </motion.div>
    </div>
  );
}
