/**
 * Session model for user authentication
 * Tracks active user sessions with expiration
 */
export interface Session {
  id: string; // UUID
  userId: number;
  expiresAt: string; // ISO 8601 timestamp
  createdAt: string;
  ipAddress: string | null;
  userAgent: string | null;
  rememberMe?: boolean; // Optional flag for extended session duration
}

/**
 * Input for creating a new session
 */
export interface CreateSessionInput {
  id: string; // UUID generated by caller
  userId: number;
  expiresAt: string;
  ipAddress?: string;
  userAgent?: string;
  rememberMe?: boolean; // Optional flag for extended session duration
}
