import { motion } from 'framer-motion';
import { X, FileText, AlertTriangle, CheckCircle, TrendingUp, Search } from 'lucide-react';
import { Card } from '../../../components/ui/Card.tsx';
import { Button } from '../../../components/ui/Button.tsx';
import type { EvidenceAnalysisResponse } from '../../../types/ai-analysis.ts';

interface EvidenceAnalysisDialogProps {
  onClose: () => void;
  analysis: EvidenceAnalysisResponse;
  isLoading?: boolean;
}

export function EvidenceAnalysisDialog({ onClose, analysis, isLoading }: EvidenceAnalysisDialogProps) {
  if (isLoading) {
    return (
      <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm p-4">
        <motion.div
          initial={{ opacity: 0, scale: 0.9 }}
          animate={{ opacity: 1, scale: 1 }}
          className="w-full max-w-4xl"
        >
          <Card variant="glass" className="p-8 text-center">
            <div className="flex flex-col items-center gap-4">
              <div className="h-12 w-12 animate-spin rounded-full border-4 border-primary-500 border-t-transparent" />
              <p className="text-lg text-white">Analyzing your evidence...</p>
              <p className="text-sm text-gray-400">Justice Companion AI is reviewing your evidence collection</p>
            </div>
          </Card>
        </motion.div>
      </div>
    );
  }

  const getImportanceColor = (importance: string) => {
    switch (importance) {
      case 'critical':
        return 'text-red-400 bg-red-900/30 border-red-700';
      case 'high':
        return 'text-orange-400 bg-orange-900/30 border-orange-700';
      case 'medium':
        return 'text-yellow-400 bg-yellow-900/30 border-yellow-700';
      case 'low':
        return 'text-green-400 bg-green-900/30 border-green-700';
      default:
        return 'text-gray-400 bg-gray-900/30 border-gray-700';
    }
  };

  const getStrengthColor = (strength: string) => {
    switch (strength) {
      case 'strong':
        return 'text-green-400 bg-green-900/30 border-green-700';
      case 'moderate':
        return 'text-yellow-400 bg-yellow-900/30 border-yellow-700';
      case 'weak':
        return 'text-orange-400 bg-orange-900/30 border-orange-700';
      case 'insufficient':
        return 'text-red-400 bg-red-900/30 border-red-700';
      default:
        return 'text-gray-400 bg-gray-900/30 border-gray-700';
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm p-4 overflow-auto">
      <motion.div
        initial={{ opacity: 0, scale: 0.9, y: 20 }}
        animate={{ opacity: 1, scale: 1, y: 0 }}
        exit={{ opacity: 0, scale: 0.9, y: 20 }}
        transition={{ type: 'spring', stiffness: 300, damping: 25 }}
        className="w-full max-w-5xl my-8"
      >
        <Card
          variant="glass"
          className="overflow-visible"
          role="dialog"
          aria-modal="true"
          aria-labelledby="evidence-analysis-dialog-title"
        >
          {/* Header */}
          <div className="flex items-center justify-between border-b border-gray-700/50 pb-4 mb-6">
            <div>
              <h2
                id="evidence-analysis-dialog-title"
                className="text-2xl font-bold text-white flex items-center gap-2"
              >
                <FileText className="h-6 w-6 text-primary-400" />
                Evidence Analysis Results
              </h2>
              <p className="text-sm text-gray-400 mt-1">
                Generated by Justice Companion AI
              </p>
            </div>
            <Button
              onClick={onClose}
              variant="ghost"
              size="sm"
              icon={<X />}
              aria-label="Close evidence analysis dialog"
              className="rounded-full"
            />
          </div>

          <div className="space-y-6 max-h-[70vh] overflow-y-auto pr-2">
            {/* Overall Assessment */}
            <section>
              <h3 className="text-lg font-semibold text-white mb-3 flex items-center gap-2">
                <TrendingUp className="h-5 w-5 text-blue-400" />
                Overall Assessment
              </h3>
              <Card variant="flat" className="p-4">
                <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-4">
                  <div className="text-center p-4 rounded-lg bg-primary-900/50">
                    <p className="text-xs text-gray-400 mb-1">Overall Strength</p>
                    <p className={`text-3xl font-bold ${getStrengthColor(analysis.overallStrength)}`}>
                      {analysis.overallStrength.toUpperCase()}
                    </p>
                  </div>
                  <div className="text-center p-4 rounded-lg bg-primary-900/50">
                    <p className="text-xs text-gray-400 mb-1">Critical Gaps</p>
                    <p className="text-3xl font-bold text-red-400">
                      {analysis.criticalGaps?.length || 0}
                    </p>
                  </div>
                  <div className="text-center p-4 rounded-lg bg-primary-900/50">
                    <p className="text-xs text-gray-400 mb-1">Strong Points</p>
                    <p className="text-3xl font-bold text-green-400">
                      {analysis.strengths?.length || 0}
                    </p>
                  </div>
                </div>
                <p className="text-sm text-gray-300">{analysis.summary}</p>
              </Card>
            </section>

            {/* Strengths */}
            {analysis.strengths && analysis.strengths.length > 0 && (
              <section>
                <h3 className="text-lg font-semibold text-white mb-3 flex items-center gap-2">
                  <CheckCircle className="h-5 w-5 text-green-400" />
                  Evidence Strengths
                </h3>
                <div className="space-y-3">
                  {analysis.strengths.map((strength, index) => (
                    <Card key={index} variant="flat" className="p-4 border-l-4 border-green-500">
                      <div className="flex items-start gap-3">
                        <CheckCircle className="h-5 w-5 text-green-400 flex-shrink-0 mt-0.5" />
                        <div className="flex-1">
                          <p className="text-sm text-gray-300 mb-1">{strength.description}</p>
                          {strength.supportingEvidence && strength.supportingEvidence.length > 0 && (
                            <div className="mt-2 text-xs text-gray-400">
                              <p className="font-medium mb-1">Supporting evidence:</p>
                              <ul className="list-disc list-inside space-y-1">
                                {strength.supportingEvidence.map((evidence, idx) => (
                                  <li key={idx}>{evidence}</li>
                                ))}
                              </ul>
                            </div>
                          )}
                        </div>
                      </div>
                    </Card>
                  ))}
                </div>
              </section>
            )}

            {/* Weaknesses */}
            {analysis.weaknesses && analysis.weaknesses.length > 0 && (
              <section>
                <h3 className="text-lg font-semibold text-white mb-3 flex items-center gap-2">
                  <AlertTriangle className="h-5 w-5 text-orange-400" />
                  Evidence Weaknesses
                </h3>
                <div className="space-y-3">
                  {analysis.weaknesses.map((weakness, index) => (
                    <Card key={index} variant="flat" className="p-4 border-l-4 border-orange-500">
                      <div className="flex items-start gap-3">
                        <AlertTriangle className="h-5 w-5 text-orange-400 flex-shrink-0 mt-0.5" />
                        <div className="flex-1">
                          <p className="text-sm text-gray-300 mb-1">{weakness.description}</p>
                          {weakness.potentialImpact && (
                            <p className="text-xs text-gray-400 italic mt-1">
                              Impact: {weakness.potentialImpact}
                            </p>
                          )}
                          {weakness.mitigation && (
                            <div className="mt-2 p-2 rounded bg-primary-900/50 border border-gray-700">
                              <p className="text-xs font-medium text-green-400 mb-1">Mitigation Strategy:</p>
                              <p className="text-xs text-gray-300">{weakness.mitigation}</p>
                            </div>
                          )}
                        </div>
                      </div>
                    </Card>
                  ))}
                </div>
              </section>
            )}

            {/* Critical Gaps */}
            {analysis.criticalGaps && analysis.criticalGaps.length > 0 && (
              <section>
                <h3 className="text-lg font-semibold text-white mb-3 flex items-center gap-2">
                  <AlertTriangle className="h-5 w-5 text-red-400" />
                  Critical Evidence Gaps
                </h3>
                <div className="space-y-3">
                  {analysis.criticalGaps.map((gap, index) => (
                    <Card key={index} variant="flat" className="p-4 border-l-4 border-red-500">
                      <div className="flex items-start justify-between gap-4">
                        <div className="flex-1">
                          <div className="flex items-center gap-2 mb-2">
                            <h4 className="font-medium text-white">{gap.missingEvidence}</h4>
                            <span
                              className={`px-2 py-1 rounded text-xs font-medium border ${getImportanceColor(gap.importance)}`}
                            >
                              {gap.importance.toUpperCase()}
                            </span>
                          </div>
                          <p className="text-sm text-gray-300 mb-2">
                            Why needed: {gap.whyNeeded}
                          </p>
                          {gap.suggestedSources && gap.suggestedSources.length > 0 && (
                            <div className="mt-3 p-3 rounded bg-primary-900/50 border border-gray-700">
                              <div className="flex items-start gap-2">
                                <Search className="h-4 w-4 text-blue-400 flex-shrink-0 mt-0.5" />
                                <div>
                                  <p className="text-xs font-medium text-blue-400 mb-2">Where to find this evidence:</p>
                                  <ul className="list-disc list-inside space-y-1 text-xs text-gray-300">
                                    {gap.suggestedSources.map((source, idx) => (
                                      <li key={idx}>{source}</li>
                                    ))}
                                  </ul>
                                </div>
                              </div>
                            </div>
                          )}
                        </div>
                      </div>
                    </Card>
                  ))}
                </div>
              </section>
            )}

            {/* Recommended Evidence */}
            {analysis.recommendedEvidence && analysis.recommendedEvidence.length > 0 && (
              <section>
                <h3 className="text-lg font-semibold text-white mb-3 flex items-center gap-2">
                  <Search className="h-5 w-5 text-blue-400" />
                  Recommended Additional Evidence
                </h3>
                <div className="space-y-3">
                  {analysis.recommendedEvidence.map((item, index) => (
                    <Card key={index} variant="flat" className="p-4">
                      <div className="flex items-start gap-3">
                        <div className="flex-shrink-0 w-8 h-8 rounded-full bg-blue-900/50 flex items-center justify-center text-sm font-bold text-blue-400 border border-blue-700">
                          {index + 1}
                        </div>
                        <div className="flex-1">
                          <h4 className="font-medium text-white mb-1">{item.type}</h4>
                          <p className="text-sm text-gray-300 mb-2">{item.description}</p>
                          <p className="text-xs text-gray-400 italic">
                            Relevance: {item.relevance}
                          </p>
                          {item.obtainmentMethod && (
                            <div className="mt-2 text-xs text-gray-400">
                              <p className="font-medium mb-1">How to obtain:</p>
                              <p>{item.obtainmentMethod}</p>
                            </div>
                          )}
                        </div>
                      </div>
                    </Card>
                  ))}
                </div>
              </section>
            )}

            {/* Next Steps */}
            {analysis.nextSteps && analysis.nextSteps.length > 0 && (
              <section>
                <h3 className="text-lg font-semibold text-white mb-3">
                  Recommended Next Steps
                </h3>
                <Card variant="flat" className="p-4">
                  <ol className="space-y-3">
                    {analysis.nextSteps.map((step, index) => (
                      <li key={index} className="flex gap-3">
                        <span className="flex-shrink-0 w-6 h-6 rounded-full bg-primary-500 text-white text-sm font-bold flex items-center justify-center">
                          {index + 1}
                        </span>
                        <p className="text-sm text-gray-300 pt-0.5">{step}</p>
                      </li>
                    ))}
                  </ol>
                </Card>
              </section>
            )}

            {/* Timeline Considerations */}
            {analysis.timelineConsiderations && (
              <section>
                <h3 className="text-lg font-semibold text-white mb-3">
                  Timeline Considerations
                </h3>
                <Card variant="flat" className="p-4">
                  <p className="text-sm text-gray-300 whitespace-pre-wrap">
                    {analysis.timelineConsiderations}
                  </p>
                </Card>
              </section>
            )}

            {/* Disclaimer */}
            <section>
              <Card variant="flat" className="p-4 bg-yellow-900/20 border border-yellow-700/50">
                <div className="flex gap-3">
                  <AlertTriangle className="h-5 w-5 text-yellow-400 flex-shrink-0 mt-0.5" />
                  <div>
                    <p className="text-sm font-medium text-yellow-200 mb-1">Important Disclaimer</p>
                    <p className="text-xs text-yellow-100/80">
                      {analysis.disclaimer ||
                        'This is an AI-generated analysis for informational purposes only. It does not constitute legal advice. For specific legal advice tailored to your situation, please consult a qualified solicitor.'}
                    </p>
                  </div>
                </div>
              </Card>
            </section>
          </div>

          {/* Footer */}
          <div className="flex gap-3 pt-6 mt-6 border-t border-gray-700/50">
            <Button
              onClick={onClose}
              variant="secondary"
              size="md"
              fullWidth
            >
              Close
            </Button>
          </div>
        </Card>
      </motion.div>
    </div>
  );
}
